### ISSUE TITLE
AttributeError: Number of inputs is not equal 1 for slice layer

### ISSUE THREAD

**Issue by emanuelcovaci** [nerox8664/onnx2keras#30]
Hi @nerox8664!

I tried to convert an ONNX model to Keras, but I received the following error

```python
Traceback (most recent call last):
  File "onnx2Keras.py", line 6, in <module>
    k_model = onnx_to_keras(onnx_model, ['input/input_data'],name_policy='renumerate')
  File "D:\EB-AI\tools\anaconda3\envs\onnx2keras-env\lib\site-packages\onnx2keras\converter.py", line 174, in onnx_to_keras
    keras_names
  File "D:\EB-AI\tools\anaconda3\envs\onnx2keras-env\lib\site-packages\onnx2keras\reshape_layers.py", line 264, in convert_slice
    raise AttributeError('Number of inputs is not equal 1 for slice layer')
AttributeError: Number of inputs is not equal 1 for slice layer
```

I converted this model  https://github.com/YunYang1994/tensorflow-yolov3 from Tensorflow to ONNX and now I need the model in Keras.

If you want I can provide the ONNX model.

Thanks!

**Comment by andreimihalcea97** [comment]
Hi @nerox8664 @emanuelcovaci !

I also tried to convert the same ONNX model to Keras and I received exactly the same error. The slice layer received 4 inputs, three of which seem to be weights.

Thanks!

**Comment by nerox8664** [comment]
Hello @emanuelcovaci @andreimihalcea97.

I fixed some errors related to `slice` layer. It now works with 4 inputs (with assumption that axes are [0, 1, ... ndims] array).

Unfortunatelly, @emanuelcovaci, your model still can't be converted due to [ONNX Resize layer](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize)

**Comment by dd1923** [comment]
@nerox8664 The onnx-tensorflow has a resize layer implementation at https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/handlers/backend/resize.py

Can you use this and add it to onnx2keras?
