### ISSUE TITLE
ImportError: cannot import name 'onnx_to_keras' from partially initialized module 'onnx2keras' (most likely due to a circular import)

### ISSUE THREAD

**Issue by jaggernaut007** [nerox8664/onnx2keras#69]
Traceback (most recent call last):
  File "onnx2keras.py", line 2, in <module>
    from onnx2keras import onnx_to_keras
  File "/home/shreyas/pose/pretrained/onnx2keras.py", line 2, in <module>
    from onnx2keras import onnx_to_keras
ImportError: cannot import name 'onnx_to_keras' from partially initialized module 'onnx2keras'

Tensorflow 2.2.0
Ubuntu 20.4

**Comment by nerox8664** [comment]
hello. You try to import a function not from the package, but from your local file. The easiest way to fix that - to rename `onnx2keras.py`.
