### ISSUE TITLE
AttributeError: Cannot convert ConvTranspose2d with groups != 1

### ISSUE THREAD

**Issue by mengzhi2** [nerox8664/onnx2keras#71]
When running the following: 
import onnx
from onnx2keras import onnx_to_keras
onnx_model = onnx.load('resnet18.onnx')
k_model = onnx_to_keras(onnx_model, ['input'])

This error occurs. Does anyone know what to do? Thanks.
Traceback (most recent call last):
  File "onnx2keras.py", line 9, in <module>
    k_model = onnx_to_keras(model, ['input'])
  File "/onnx2keras/onnx2keras/converter.py", line 180, in onnx_to_keras
    keras_names
  File "/onnx2keras/onnx2keras/convolution_layers.py", line 258, in convert_convtranspose
    raise AttributeError('Cannot convert ConvTranspose2d with groups != 1')
AttributeError: Cannot convert ConvTranspose2d with groups != 1

**Comment by LaCandela** [comment]
I had the same problem.

**Comment by nerox8664** [comment]
Hello @LaCandela @mengzhi2 .

Unfortunately, Keras doesn't support groupped ConvTranspose2d : https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2DTranspose

In future versions I will implement this feature as I did for Conv2d (using lambdas).

**Comment by mengzhi2** [comment]
Got it. Thanks for your reply.
Looking forward to your future work.
