### ISSUE TITLE
AttributeError: Not implemented

### ISSUE THREAD

**Issue by Tian14267** [nerox8664/onnx2keras#74]
I covert my onnx model,and get this problem:
**............
............
DEBUG:onnx2keras:...
DEBUG:onnx2keras:Check if all inputs are available:
DEBUG:onnx2keras:Check input 0 (name 565).
DEBUG:onnx2keras:Check input 1 (name 567).
DEBUG:onnx2keras:Check input 2 (name 568).
DEBUG:onnx2keras:Check input 3 (name 566).
DEBUG:onnx2keras:... found all, continue
DEBUG:onnx2keras:slice:Slice numpy constants
Traceback (most recent call last):
  File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/onnx2ke.py", line 12, in <module>
    onnx_to_ke()
  File "/home/fffan/fffan_files/Experiment/Example/onnx2pb/onnx2ke.py", line 9, in onnx_to_ke
    k_model = onnx_to_keras(onnx_model, ['input'])
  File "/home/fffan/.local/lib/python3.7/site-packages/onnx2keras/converter.py", line 181, in onnx_to_keras
    keras_names
  File "/home/fffan/.local/lib/python3.7/site-packages/onnx2keras/reshape_layers.py", line 296, in convert_slice
    raise AttributeError('Not implemented')
AttributeError: Not implemented**
How can I solve this problem?

**Comment by nerox8664** [comment]
Hello @Tian14267.

Can you please share the model you try to convert?

**Comment by Tian14267** [comment]
My model is saved in Baidu Netdisk:
Link:  https://pan.baidu.com/s/15ILpwpoJIRif8ZbWnVbmqw 
password：2rtc

Looking forward to your reply
@nerox8664

**Comment by arossbach10** [comment]
I have the same issue.
Do you need more information?

**Comment by try-catch-repeat** [comment]
Did you somehow resolve this issue?
